config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :project, only: [:create, :update, :destroy, :set_priority] do
    resources :tasks, only: [:create, :update, :destroy] do
    end
  end
  root 'project#index'
  post '/drag-tasks/', to: 'project#set_priority', as: :set_prioritys
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
    user ||= User.new # guest user (not logged in)
    
    alias_action :create, :read, :update, :destroy, to: :crud
    
    if !user.new_record?
      can :crud, [Project, Task]
      can :create_task, Project
      can :set_priority, Project
    else
      cannot :crud, [Project, Task]
    end
    
    
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :target, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
  check_authorization :unless => :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.new_user_session_path, alert: exception.message
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  load_and_authorize_resource :through => :current_user
  
  def index
    @task = Task.new
  end
  
  def create
    @project = Project.new(user_id: current_user.id)
    if @project.save
      flash[:notice] = "New project was successfully created"
    else
      flash[:alert] = "New project wasn't successfully created"
    end
    redirect_to root_path
  end
  
  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "Project was successfully deleted"
    else
      flash[:alert] = "Project wasn't successfully deleted"
    end
    redirect_to root_path
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update(projects_params)
      flash[:notice] = "Project was successfully updated"
    else
      flash[:alert] = "Project wasn't successfully updated"
    end
    redirect_to root_path
  end
  
  def set_priority
    @project = Project.find(params[:project_id])
    @ids = params[:ids]
    @count = params[:ids].count
    @count.times do |index|
      @task = @project.tasks.find(@ids[index])
      @task.update(priority: index.to_i)
    end
  end
  
  private

  def tasks_params
    params.require(:task).permit(:target)
  end
  
  def projects_params
    params.require(:project).permit(:name)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource :project
  load_and_authorize_resource :task, :through => :project
  
  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      flash[:notice] = "New task was successfully created"
    else
      flash[:alert] = "New task wasn't successfully create" 
    end
    redirect_to root_path
  end
  
  def destroy
    @task = @project.tasks.find(params[:id])
    if @task.destroy
      flash[:notice] = "Task was deleted"
    else
      flash[:alert] = "Task was not deleted"
    end
    redirect_to root_path
  end
  
  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "New task was successfully updated"
    else
      flash[:alert] = "New task wasn't successfully updated"
    end
    redirect_to root_path
  end
  
  private

  def task_params
    params.require(:task).permit(:target)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'jquery', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  </head>

  <body>
    <wrapper>
      <p>simple todo lists</p>
      <p>from ruby garage</p>
    </wrapper>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/project/_tasks.html.erb
<div class="one-task data-id-<%= task.id %>">
  <div class="task-state">
    <%= check_box_tag :state, task.state %>
  </div>
  <div class="task-target">
    <%= task.target %>
  </div>
  <%= form_for task, url: project_task_path(task.project.id, task.id), method: :put do |f| %>
    <div class="task-input-target">
      <%= f.text_field :target, placeholder: task.target %>
    </div>
    <div class="settings_task">
      <div class="task-drag-drop"></div>
      <div class="get-task-edit"><%= image_tag("http://res.cloudinary.com/nmetau/image/upload/v1504876352/favicon_21_qyaaen.ico") %></div>
       <div class="get-tasks-input-submit">
          <%= f.submit "" %>
        </div>
      <div class="task-delete"><%= link_to image_tag("http://res.cloudinary.com/nmetau/image/upload/v1504876495/favicon_22_elcsbm.ico"),  project_task_path(task.project.id, task.id), method: :delete %></div>
    </div>
  <% end %>
</div>

app/views/project/index.html.erb
<% current_user.projects.each do |project| %>
  <div class="project">
    <div class="project-head">
      <div class="project-calendar"><%= link_to image_tag("http://res.cloudinary.com/nmetau/image/upload/v1504796437/favicon_10_gy7dvg.ico"), "#" %></div>
      <div class="project-name">
        <%= project.name %>
      </div>
      <div class="project-edit-name">
      <%= form_for project, url: project_path(project.id), method: :put do |f| %>
          <%= f.text_field :name, placeholder: project.name %>
        <div class="get-edit-input-submit">
          <%= f.submit "" %>
        </div>
      <% end %>
      </div>
      <div class="get-edit-input"></div>
      <div class="project-delete-name">
        <%= link_to image_tag("http://res.cloudinary.com/nmetau/image/upload/v1504801309/favicon_18_gslmgk.ico"), project_path(project.id), method: :delete %>
      </div>
    </div>
    <div class="project-add-task">
      <div class="add-image"></div>
      <div class="task-construction">
        <%= form_for @task, url: project_tasks_path(project.id), method: :post do |f| %>
          <%= f.text_field :target, placeholder: "Start typing here to create a task..." %>
          <%= f.submit "Add Task" %>
        <% end %>
      </div>
    </div>
    <div class="project-content project-<%= project.id %>-id">
      <% project.tasks.order(:priority).each do |task| %>
        <%= render partial: "tasks", locals: { task: task } %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="add-project-button">
  <%= link_to "Add new project", project_index_path, method: :post %>
</div>

<div class="exit">
  <%= link_to "Exit", destroy_user_session_path, :method => :delete %>
</div>